server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mailing_service
    username: postgres
    password: 1111

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sdragunovskiy@gmail.com
    password: mpju pcjy nltk ffst
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  main:
#      allow-circular-references: true